# ===== REPLICATION SETTINGS (MASTER) =====

# Spécifier le fichier pg_hba.conf monté
hba_file = '/etc/postgresql/pg_hba.conf'

# Listen on all network interfaces
listen_addresses = '*'
# Enable WAL (Write-Ahead Logging)
# Enregistre TOUS les changements
wal_level = replica

# Maximum nombre de connexions esclaves
max_wal_senders = 3

# Garder les logs de réplication
wal_keep_size = 1GB

# Timeout pour les esclaves
wal_sender_timeout = 60s

# Port
port = 5432

# Log settings (pour déboguer si problème)
log_statement = 'all'
log_replication_commands = on