local   all             all                                     trust
hostnossl    replication     replicator      0.0.0.0/0               trust
hostnossl    all             all             0.0.0.0/0               trust