# ===== REPLICATION SETTINGS (SLAVE) =====

# Spécifier le fichier pg_hba.conf monté
hba_file = '/etc/postgresql/pg_hba.conf'

# Listen on all network interfaces
listen_addresses = '*'

# Mode standby chaud
# Permet de faire des LECTURES sur le slave
hot_standby = on

# Timeout pour se reconnecter au master
wal_retrieve_retry_interval = 5s

# Port
port = 5432

# Log settings
log_statement = 'all'